==========================================
SLURM_JOB_ID = 721248
SLURM_NODELIST = gnode012
SLURM_JOB_GPUS = 0
==========================================
ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'cuda/11.6'
ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'cudnn/8.4.0-cuda-11.6'
/var/spool/slurmd/job721248/slurm_script: line 10: /home/sriaish/keras/bin/activate: No such file or directory
Start learning FSA
75
data_set/BP_15_15_35_25
states:  7 trial:  0
done
--- 92.81559491157532 seconds ---
data_set/BP_15_15_35_25
states:  7 trial:  1
done
--- 1764.74196600914 seconds ---
data_set/BP_15_15_35_25
states:  7 trial:  2
done
--- 3536.0720217227936 seconds ---
data_set/BP_15_15_35_25
states:  7 trial:  3
done
--- 493.31786012649536 seconds ---
data_set/BP_15_15_35_25
states:  7 trial:  4
done
--- 879.9819257259369 seconds ---
data_set/BP_15_15_35_25
states:  7 trial:  5
done
--- 26.713246822357178 seconds ---
data_set/BP_15_15_35_25
states:  7 trial:  6
done
--- 5059.064175367355 seconds ---
data_set/BP_15_15_35_25
states:  7 trial:  7
done
--- 3475.0247254371643 seconds ---
data_set/BP_15_15_35_25
states:  7 trial:  8
done
--- 768.4459745883942 seconds ---
data_set/BP_15_15_35_25
states:  7 trial:  9
done
--- 11.891286611557007 seconds ---
--- 16108.069013118744 seconds for all trials---
========================================================
Checking Accuracy of learned FSAs
data_set/BP_15_15_35_25
states:  5 trial:  0
Traceback (most recent call last):
  File "test.py", line 108, in <module>
    delta = load("results/delta/new_" + file_name + "_" + sys.argv[2] + "_" + str(i_try))
  File "/home/sriaish/NSE_PlanningAgent/Whole 15/misc.py", line 4, in load
    file_to_read = open(name, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'results/delta/new_BP_15_15_35_25_5_0'
running agent
Traceback (most recent call last):
  File "FSA_Agent_combVar.py", line 229, in <module>
    delta = load("results/delta/new_" + file_name + "_" + sys.argv[13] + "_best")
  File "/home/sriaish/NSE_PlanningAgent/Whole 15/misc.py", line 4, in load
    file_to_read = open(name, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'results/delta/new_BP_15_15_35_25_7_best'
16111
--------------------
Traceback (most recent call last):
  File "FSA_Agent_combVar.py", line 229, in <module>
    delta = load("results/delta/new_" + file_name + "_" + sys.argv[13] + "_best")
  File "/home/sriaish/NSE_PlanningAgent/Whole 15/misc.py", line 4, in load
    file_to_read = open(name, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'results/delta/new_BP_15_15_35_25_7_best'
0
--------------------
running agent
Traceback (most recent call last):
  File "FSA_Agent_combVar.py", line 229, in <module>
    delta = load("results/delta/new_" + file_name + "_" + sys.argv[13] + "_best")
  File "/home/sriaish/NSE_PlanningAgent/Whole 15/misc.py", line 4, in load
    file_to_read = open(name, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'results/delta/new_BP_15_15_35_25_7_best'
0
--------------------
